server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libraryUserdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: test1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: library-user-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
